services:
  clipman-api:
    build: .
    container_name: clipman-api
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - clipman-db
  clipman-db:
    image: mongo:latest
    container_name: clipman-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb_data:/data/db
      - ./docker/mongo_logs:/var/log/mongodb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
